[features]
seeds = false
skip-lint = false
[programs.localnet]
chain_tree = "DaZske7f7vZnLmXrdp1LyAv7VDgdayKbRD2rWBgnEqud"

[programs.devnet]
chain_tree = "DaZske7f7vZnLmXrdp1LyAv7VDgdayKbRD2rWBgnEqud"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/saicoder/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
